export const FLOWOPS_ROLES = [
  {
    id: "alex",
    name: "Alex",
    title: "Strategy Director",
    accent: "#60A5FA",
    avatarThumb: "/assets/solution-design/avatars/alex_strategy_director_thumb.png",
    avatarFull: "/assets/solution-design/avatars/alex_strategy_director_full.png",
    position: {
      desktop: { x: 24, y: 26 },
      mobile: { x: 24, y: 23 },
    },
  },
  {
    id: "iris",
    name: "Iris",
    title: "Intelligence Analyst",
    accent: "#22D3EE",
    avatarThumb: "/assets/solution-design/avatars/iris_intelligence_analyst_thumb.png",
    avatarFull: "/assets/solution-design/avatars/iris_intelligence_analyst_full.png",
    position: {
      desktop: { x: 49, y: 15 },
      mobile: { x: 50, y: 13 },
    },
  },
  {
    id: "blake",
    name: "Blake",
    title: "Systems Architect",
    accent: "#818CF8",
    avatarThumb: "/assets/solution-design/avatars/blake_systems_architect_thumb.png",
    avatarFull: "/assets/solution-design/avatars/blake_systems_architect_full.png",
    position: {
      desktop: { x: 12, y: 50 },
      mobile: { x: 10, y: 52 },
    },
  },
  {
    id: "chris",
    name: "Chris",
    title: "Automation Engineer",
    accent: "#34D399",
    avatarThumb: "/assets/solution-design/avatars/chris_automation_engineer_thumb.png",
    avatarFull: "/assets/solution-design/avatars/chris_automation_engineer_full.png",
    position: {
      desktop: { x: 22, y: 74 },
      mobile: { x: 22, y: 79 },
    },
  },
  {
    id: "dana",
    name: "Dana",
    title: "Operations & Finance Manager",
    accent: "#F59E0B",
    avatarThumb: "/assets/solution-design/avatars/dana_operations_finance_manager_thumb.png",
    avatarFull: "/assets/solution-design/avatars/dana_operations_finance_manager_full.png",
    position: {
      desktop: { x: 66, y: 78 },
      mobile: { x: 74, y: 79 },
    },
  },
  {
    id: "mason",
    name: "Mason",
    title: "Growth Architect",
    accent: "#06B6D4",
    avatarThumb: "/assets/solution-design/avatars/mason_growth_architect_thumb.png",
    avatarFull: "/assets/solution-design/avatars/mason_growth_architect_full.png",
    position: {
      desktop: { x: 76, y: 25 },
      mobile: { x: 77, y: 24 },
    },
  },
  {
    id: "sofia",
    name: "Sofia",
    title: "Copy Chief",
    accent: "#A78BFA",
    avatarThumb: "/assets/solution-design/avatars/sofia_copy_chief_thumb.png",
    avatarFull: "/assets/solution-design/avatars/sofia_copy_chief_full.png",
    position: {
      desktop: { x: 86, y: 50 },
      mobile: { x: 90, y: 53 },
    },
  },
  {
    id: "ava",
    name: "Ava",
    title: "Creative Director",
    accent: "#F472B6",
    avatarThumb: "/assets/solution-design/avatars/ava_creative_director_thumb.png",
    avatarFull: "/assets/solution-design/avatars/ava_creative_director_full.png",
    position: {
      desktop: { x: 49, y: 88 },
      mobile: { x: 50, y: 92 },
    },
  },
];

export const FLOWOPS_WORKFLOWS = [
  {
    id: "website-system",
    label: "Website System",
    shortLabel: "Website",
    accent: "#60A5FA",
    summary: "Combines strategy, architecture, copy, and creative direction into a production-ready web system.",
    activeRoleIds: ["alex", "blake", "sofia", "ava", "mason"],
    skills: [
      "Site architecture planning",
      "Page hierarchy design",
      "Conversion-aware messaging",
      "Visual direction alignment",
      "Growth pathway mapping",
    ],
    outputs: [
      "Website structure",
      "Page wireframe logic",
      "Messaging framework",
      "Creative direction brief",
      "Conversion page blueprint",
    ],
  },
  {
    id: "lead-conversion",
    label: "Lead Conversion System",
    shortLabel: "Lead Conversion",
    accent: "#22D3EE",
    summary: "Routes strategy, copy, systems, and automation roles into a conversion-ready acquisition flow.",
    activeRoleIds: ["alex", "blake", "chris", "dana", "mason", "sofia"],
    skills: [
      "Conversion strategy",
      "Funnel architecture",
      "Lead capture flow design",
      "CRM automation setup",
      "Follow-up sequence logic",
      "Landing page copy",
    ],
    outputs: [
      "Landing page structure",
      "Lead capture form",
      "CRM pipeline",
      "Follow-up automation",
      "Conversion tracking",
    ],
  },
  {
    id: "automation-system",
    label: "Automation System",
    shortLabel: "Automation",
    accent: "#34D399",
    summary: "Activates architecture, engineering, and operations roles to translate opportunity into automated execution.",
    activeRoleIds: ["blake", "chris", "dana", "iris"],
    skills: [
      "Process mapping",
      "Automation workflow design",
      "System integration planning",
      "Operational controls",
      "Intelligence signal handling",
    ],
    outputs: [
      "Automation blueprint",
      "Trigger logic map",
      "Ops control layer",
      "Integration checklist",
      "Exception handling flow",
    ],
  },
  {
    id: "marketing-system",
    label: "Marketing System",
    shortLabel: "Marketing",
    accent: "#A78BFA",
    summary: "Brings together insight, strategy, copy, creative, and growth roles to assemble campaign-ready systems.",
    activeRoleIds: ["alex", "iris", "mason", "sofia", "ava"],
    skills: [
      "Audience signal analysis",
      "Offer positioning",
      "Campaign message development",
      "Creative asset planning",
      "Growth channel orchestration",
    ],
    outputs: [
      "Campaign architecture",
      "Content messaging system",
      "Creative brief stack",
      "Growth channel plan",
      "Performance tracking map",
    ],
  },
];

export const DEFAULT_WORKFLOW_ID = "lead-conversion";
export const SOLUTION_HUB = {
  x: 50,
  y: 54,
  labelTop: "Solution Design",
  labelBottom: "Engine",
};
