export const FLOWOPS_ROLES = [
  {
    id: "alex",
    name: "Alex",
    title: "Strategy Director",
    titleTh: "ผู้อำนวยการกลยุทธ์",
    accent: "#60A5FA",
    summary: "Owns strategic direction and decides which opportunities, offers, and positioning paths are worth pursuing.",
    summaryTh: "กำหนดทิศทางเชิงกลยุทธ์และตัดสินใจว่าโอกาส ข้อเสนอ และแนวทางการวางตำแหน่งใดควรเดินหน้าต่อ",
    details: [
      "evaluate ideas and business opportunities",
      "define market positioning",
      "create offers and service structures",
      "guide high-level strategic decisions across workflows",
    ],
    detailsTh: [
      "ประเมินไอเดียและโอกาสทางธุรกิจ",
      "กำหนดการวางตำแหน่งทางการตลาด",
      "ออกแบบข้อเสนอและโครงสร้างบริการ",
      "กำกับการตัดสินใจเชิงกลยุทธ์ในทุกเวิร์กโฟลว์",
    ],
    avatarThumb: "/assets/solution-design/avatars/alex_strategy_director_thumb.png",
    avatarFull: "/assets/solution-design/avatars/alex_strategy_director_full.png",
    position: {
      desktop: { x: 28, y: 26 },
      mobile: { x: 27, y: 23 },
    },
  },
  {
    id: "iris",
    name: "Iris",
    title: "Intelligence Analyst",
    titleTh: "นักวิเคราะห์อินเทลลิเจนซ์",
    accent: "#22D3EE",
    summary: "Owns research intelligence and transforms raw information into signals, risks, and opportunities.",
    summaryTh: "รับผิดชอบงานวิจัยเชิงอินเทลลิเจนซ์และแปลงข้อมูลดิบให้เป็นสัญญาณ ความเสี่ยง และโอกาส",
    details: [
      "perform market and industry research",
      "analyze competitors and offers",
      "identify patterns, signals, and gaps",
      "surface risks and opportunities for downstream decisions",
    ],
    detailsTh: [
      "ทำวิจัยตลาดและอุตสาหกรรม",
      "วิเคราะห์คู่แข่งและข้อเสนอ",
      "ระบุรูปแบบ สัญญาณ และช่องว่าง",
      "สรุปความเสี่ยงและโอกาสเพื่อใช้ตัดสินใจต่อ",
    ],
    avatarThumb: "/assets/solution-design/avatars/iris_intelligence_analyst_thumb.png",
    avatarFull: "/assets/solution-design/avatars/iris_intelligence_analyst_full.png",
    position: {
      desktop: { x: 49, y: 15 },
      mobile: { x: 50, y: 13 },
    },
  },
  {
    id: "blake",
    name: "Blake",
    title: "Systems Architect",
    titleTh: "สถาปนิกระบบ",
    accent: "#818CF8",
    summary: "Owns operational and technical design for automations, AI workflows, CRM structures, and scalable solutions.",
    summaryTh: "รับผิดชอบการออกแบบเชิงปฏิบัติการและเทคนิคสำหรับระบบอัตโนมัติ เวิร์กโฟลว์ AI โครงสร้าง CRM และโซลูชันที่ขยายได้",
    details: [
      "design automation systems",
      "define AI-enabled workflows",
      "map technical architecture",
      "choose suitable tools and integrations",
    ],
    detailsTh: [
      "ออกแบบระบบอัตโนมัติ",
      "กำหนดเวิร์กโฟลว์ที่ขับเคลื่อนด้วย AI",
      "วางสถาปัตยกรรมทางเทคนิค",
      "เลือกเครื่องมือและการเชื่อมต่อที่เหมาะสม",
    ],
    avatarThumb: "/assets/solution-design/avatars/blake_systems_architect_thumb.png",
    avatarFull: "/assets/solution-design/avatars/blake_systems_architect_full.png",
    position: {
      desktop: { x: 12, y: 50 },
      mobile: { x: 10, y: 52 },
    },
  },
  {
    id: "chris",
    name: "Chris",
    title: "Automation Engineer",
    titleTh: "วิศวกรระบบอัตโนมัติ",
    accent: "#34D399",
    summary: "Owns implementation-oriented automation work and translates architecture into practical technical execution.",
    summaryTh: "รับผิดชอบการลงมือสร้างระบบอัตโนมัติและแปลงสถาปัตยกรรมให้เป็นการดำเนินงานทางเทคนิคที่ใช้ได้จริง",
    details: [
      "implement automations",
      "build integrations",
      "configure workflows and tools",
      "support deployment of client systems",
    ],
    detailsTh: [
      "ติดตั้งและพัฒนาระบบอัตโนมัติ",
      "สร้างการเชื่อมต่อระหว่างระบบ",
      "ตั้งค่าเวิร์กโฟลว์และเครื่องมือ",
      "สนับสนุนการนำระบบไปใช้งานกับลูกค้า",
    ],
    avatarThumb: "/assets/solution-design/avatars/chris_automation_engineer_thumb.png",
    avatarFull: "/assets/solution-design/avatars/chris_automation_engineer_full.png",
    position: {
      desktop: { x: 26, y: 74 },
      mobile: { x: 26, y: 79 },
    },
  },
  {
    id: "dana",
    name: "Dana",
    title: "Operations & Finance Manager",
    titleTh: "ผู้จัดการปฏิบัติการและการเงิน",
    accent: "#F59E0B",
    summary: "Owns operational records, documentation, continuity, and finance administration inside the FlowOps OS.",
    summaryTh: "ดูแลงานบันทึกการปฏิบัติการ เอกสาร ความต่อเนื่อง และการจัดการด้านการเงินภายใน FlowOps OS",
    details: [
      "manage project tracking and records",
      "update Notion pages and databases",
      "generate SOPs and documentation",
      "create and maintain company documents",
      "handle invoices and payment tracking",
      "support onboarding and delivery operations",
    ],
    detailsTh: [
      "ดูแลการติดตามโปรเจกต์และบันทึกข้อมูล",
      "อัปเดตหน้าและฐานข้อมูลใน Notion",
      "จัดทำ SOP และเอกสารประกอบ",
      "สร้างและดูแลเอกสารบริษัท",
      "ดูแลใบแจ้งหนี้และการติดตามการชำระเงิน",
      "สนับสนุนการออนบอร์ดและการส่งมอบงาน",
    ],
    avatarThumb: "/assets/solution-design/avatars/dana_operations_finance_manager_thumb.png",
    avatarFull: "/assets/solution-design/avatars/dana_operations_finance_manager_full.png",
    position: {
      desktop: { x: 74, y: 74 },
      mobile: { x: 74, y: 79 },
    },
  },
  {
    id: "mason",
    name: "Mason",
    title: "Growth Architect",
    titleTh: "สถาปนิกการเติบโต",
    accent: "#06B6D4",
    summary: "Owns funnel and acquisition-system design inside the FlowOps OS.",
    summaryTh: "รับผิดชอบการออกแบบฟันเนลและระบบได้มาซึ่งลูกค้าภายใน FlowOps OS",
    details: [
      "design funnels and conversion paths",
      "structure campaigns and paid traffic flows",
      "define growth strategy across channels",
      "connect ads, landing pages, and conversion systems",
    ],
    detailsTh: [
      "ออกแบบฟันเนลและเส้นทางคอนเวอร์ชัน",
      "วางโครงสร้างแคมเปญและการไหลของทราฟฟิกแบบชำระเงิน",
      "กำหนดกลยุทธ์การเติบโตข้ามช่องทาง",
      "เชื่อมโฆษณา แลนดิ้งเพจ และระบบคอนเวอร์ชันเข้าด้วยกัน",
    ],
    avatarThumb: "/assets/solution-design/avatars/mason_growth_architect_thumb.png",
    avatarFull: "/assets/solution-design/avatars/mason_growth_architect_full.png",
    position: {
      desktop: { x: 72, y: 25 },
      mobile: { x: 73, y: 24 },
    },
  },
  {
    id: "sofia",
    name: "Sofia",
    title: "Copy Chief",
    titleTh: "หัวหน้าทีมคอนเทนต์ขาย",
    accent: "#A78BFA",
    summary: "Owns persuasive messaging across offers, landing pages, ads, emails, scripts, and sales assets.",
    summaryTh: "รับผิดชอบข้อความเชิงโน้มน้าวในข้อเสนอ แลนดิ้งเพจ โฆษณา อีเมล สคริปต์ และสื่อการขาย",
    details: [
      "write persuasive copy for pages and campaigns",
      "define messaging angles and hooks",
      "create email and follow-up copy",
      "shape scripts for ads, videos, and presenters",
    ],
    detailsTh: [
      "เขียนข้อความขายสำหรับหน้าเว็บและแคมเปญ",
      "กำหนดมุมสื่อสารและฮุกข้อความ",
      "สร้างอีเมลและข้อความติดตามผล",
      "วางสคริปต์สำหรับโฆษณา วิดีโอ และผู้นำเสนอ",
    ],
    avatarThumb: "/assets/solution-design/avatars/sofia_copy_chief_thumb.png",
    avatarFull: "/assets/solution-design/avatars/sofia_copy_chief_full.png",
    position: {
      desktop: { x: 86, y: 50 },
      mobile: { x: 90, y: 53 },
    },
  },
  {
    id: "ava",
    name: "Ava",
    title: "Creative Director",
    titleTh: "ผู้อำนวยการฝ่ายสร้างสรรค์",
    accent: "#F472B6",
    summary: "Owns visual and creative direction across websites, campaigns, ads, and presentation assets.",
    summaryTh: "รับผิดชอบทิศทางภาพและความคิดสร้างสรรค์สำหรับเว็บไซต์ แคมเปญ โฆษณา และสื่อพรีเซนต์",
    details: [
      "create visual concepts for campaigns",
      "define creative briefs",
      "support UGC, product visuals, and video ad concepts",
      "ensure creative assets align with strategy and messaging",
    ],
    detailsTh: [
      "สร้างแนวคิดภาพสำหรับแคมเปญ",
      "กำหนดครีเอทีฟบรีฟ",
      "สนับสนุนแนวคิด UGC ภาพสินค้า และวิดีโอโฆษณา",
      "ดูแลให้สื่อสร้างสรรค์สอดคล้องกับกลยุทธ์และข้อความ",
    ],
    avatarThumb: "/assets/solution-design/avatars/ava_creative_director_thumb.png",
    avatarFull: "/assets/solution-design/avatars/ava_creative_director_full.png",
    position: {
      desktop: { x: 49, y: 84 },
      mobile: { x: 50, y: 88 },
    },
  },
];

export const FLOWOPS_WORKFLOWS = [
  {
    id: "website-system",
    label: "Website System",
    labelTh: "ระบบเว็บไซต์",
    shortLabel: "Website",
    shortLabelTh: "เว็บไซต์",
    accent: "#60A5FA",
    summary: "Combines strategy, architecture, copy, and creative direction into a production-ready web system.",
    summaryTh: "ผสานกลยุทธ์ สถาปัตยกรรม เนื้อหา และทิศทางสร้างสรรค์ให้เป็นระบบเว็บไซต์ที่พร้อมใช้งานจริง",
    activeRoleIds: ["alex", "blake", "sofia", "ava", "mason"],
    skills: [
      "Site architecture planning",
      "Page hierarchy design",
      "Conversion-aware messaging",
      "Visual direction alignment",
      "Growth pathway mapping",
    ],
    skillsTh: [
      "วางแผนสถาปัตยกรรมเว็บไซต์",
      "ออกแบบลำดับชั้นของหน้า",
      "กำหนดข้อความที่รองรับคอนเวอร์ชัน",
      "จัดแนวทิศทางภาพ",
      "วางเส้นทางการเติบโต",
    ],
    outputs: [
      "Website structure",
      "Page wireframe logic",
      "Messaging framework",
      "Creative direction brief",
      "Conversion page blueprint",
    ],
    outputsTh: [
      "โครงสร้างเว็บไซต์",
      "ตรรกะไวร์เฟรมของหน้า",
      "กรอบข้อความหลัก",
      "ครีเอทีฟบรีฟ",
      "บลูพรินต์หน้าคอนเวอร์ชัน",
    ],
  },
  {
    id: "lead-conversion",
    label: "Lead Conversion System",
    labelTh: "ระบบแปลงลีด",
    shortLabel: "Lead Conversion",
    shortLabelTh: "แปลงลีด",
    accent: "#22D3EE",
    summary: "Routes strategy, copy, systems, and automation roles into a conversion-ready acquisition flow.",
    summaryTh: "เชื่อมบทบาทด้านกลยุทธ์ เนื้อหา ระบบ และอัตโนมัติให้กลายเป็นเส้นทางได้มาซึ่งลูกค้าที่พร้อมคอนเวอร์ชัน",
    activeRoleIds: ["alex", "blake", "chris", "dana", "mason", "sofia"],
    skills: [
      "Conversion strategy",
      "Funnel architecture",
      "Lead capture flow design",
      "CRM automation setup",
      "Follow-up sequence logic",
      "Landing page copy",
    ],
    skillsTh: [
      "กลยุทธ์คอนเวอร์ชัน",
      "สถาปัตยกรรมฟันเนล",
      "ออกแบบการเก็บข้อมูลลีด",
      "ตั้งค่า CRM อัตโนมัติ",
      "ตรรกะลำดับการติดตามผล",
      "ข้อความแลนดิ้งเพจ",
    ],
    outputs: [
      "Landing page structure",
      "Lead capture form",
      "CRM pipeline",
      "Follow-up automation",
      "Conversion tracking",
    ],
    outputsTh: [
      "โครงสร้างแลนดิ้งเพจ",
      "ฟอร์มเก็บข้อมูลลีด",
      "ไปป์ไลน์ใน CRM",
      "ระบบติดตามผลอัตโนมัติ",
      "ระบบติดตามคอนเวอร์ชัน",
    ],
  },
  {
    id: "automation-system",
    label: "Automation System",
    labelTh: "ระบบอัตโนมัติ",
    shortLabel: "Automation",
    shortLabelTh: "อัตโนมัติ",
    accent: "#34D399",
    summary: "Activates architecture, engineering, and operations roles to translate opportunity into automated execution.",
    summaryTh: "เปิดใช้งานบทบาทด้านสถาปัตยกรรม วิศวกรรม และปฏิบัติการเพื่อแปลงโอกาสให้เป็นการดำเนินงานแบบอัตโนมัติ",
    activeRoleIds: ["blake", "chris", "dana", "iris"],
    skills: [
      "Process mapping",
      "Automation workflow design",
      "System integration planning",
      "Operational controls",
      "Intelligence signal handling",
    ],
    skillsTh: [
      "แมปกระบวนการทำงาน",
      "ออกแบบเวิร์กโฟลว์อัตโนมัติ",
      "วางแผนการเชื่อมต่อระบบ",
      "กำหนดการควบคุมการปฏิบัติการ",
      "จัดการสัญญาณอินเทลลิเจนซ์",
    ],
    outputs: [
      "Automation blueprint",
      "Trigger logic map",
      "Ops control layer",
      "Integration checklist",
      "Exception handling flow",
    ],
    outputsTh: [
      "บลูพรินต์ระบบอัตโนมัติ",
      "แผนตรรกะทริกเกอร์",
      "ชั้นควบคุมการปฏิบัติการ",
      "เช็กลิสต์การเชื่อมต่อระบบ",
      "โฟลว์จัดการข้อยกเว้น",
    ],
  },
  {
    id: "marketing-system",
    label: "Marketing System",
    labelTh: "ระบบการตลาด",
    shortLabel: "Marketing",
    shortLabelTh: "การตลาด",
    accent: "#A78BFA",
    summary: "Brings together insight, strategy, copy, creative, and growth roles to assemble campaign-ready systems.",
    summaryTh: "รวมบทบาทด้านอินไซต์ กลยุทธ์ คอนเทนต์ ครีเอทีฟ และการเติบโตเพื่อประกอบเป็นระบบแคมเปญที่พร้อมใช้งาน",
    activeRoleIds: ["alex", "iris", "mason", "sofia", "ava"],
    skills: [
      "Audience signal analysis",
      "Offer positioning",
      "Campaign message development",
      "Creative asset planning",
      "Growth channel orchestration",
    ],
    skillsTh: [
      "วิเคราะห์สัญญาณของกลุ่มเป้าหมาย",
      "วางตำแหน่งข้อเสนอ",
      "พัฒนาข้อความของแคมเปญ",
      "วางแผนสินทรัพย์ครีเอทีฟ",
      "ประสานช่องทางการเติบโต",
    ],
    outputs: [
      "Campaign architecture",
      "Content messaging system",
      "Creative brief stack",
      "Growth channel plan",
      "Performance tracking map",
    ],
    outputsTh: [
      "สถาปัตยกรรมแคมเปญ",
      "ระบบข้อความคอนเทนต์",
      "ชุดครีเอทีฟบรีฟ",
      "แผนช่องทางการเติบโต",
      "แผนติดตามผลลัพธ์",
    ],
  },
];

export const DEFAULT_WORKFLOW_ID = "website-system";
export const SOLUTION_HUB = {
  x: 50,
  y: 54,
  labelTop: "Solution Architecture",
  labelBottom: "Engine",
  labelTopTh: "สถาปัตยกรรมโซลูชัน",
  labelBottomTh: "เอนจิน",
};
